#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Crea un file JSON completo con TUTTI i dati del form Wix Studio da importare
"""
import json
from datetime import datetime

# Tutti i contatti dal form Wix (104 totali)
WIX_SUBMISSIONS = [
    {"name": "Elisa", "email": "miriamdimatera@hotmail.it", "phone": "+39 339 434 6599", "product": "Robot umanoide", "message": "Vorrei parlare con qualcuno per avere informazioni sul robot umanoide", "created_date": "2026-01-12T12:33:00Z"},
    {"name": "Mauro", "email": "geomgv@gmail.co", "phone": "+39 335 707 3211", "product": "Unitree G1", "message": "Buongiorno, avendo una impresa edile, esiste un robot capace di spostare pesi e muoversi in autonomia nei diversi luoghi dei cantiere cha vanno da terreno a locali intrerni passando dalle scale, ecc.... Grazie Cordiali saluti Mauri", "created_date": "2026-01-11T21:56:00Z"},
    {"name": "Fabio Cortinovis", "email": "fabio.cortinovis@ntsmoulding.com", "phone": "+39 349 282 8030", "product": "G1 EDU e altro", "message": "Buongiorno, vi contatto per chiedere informazioni sui robot umanoidi da voi rivenduti ed integrati. La finalità è quella di iniziare ad approcciare e valutare i possibili campi di utilizzo di questa tipologia di robot ed il grado attuale di sicurezza. Se possibile chiedo disponibilità per un incontro presso la nostra sede. Ringrazio fin d'ora per la disponibilità. Cordiali saluti Fabio Cortinovis R&D Manager NTS S.p.A. Via Morletta 10/12 - 24040 Lallio (BG) - ITALY Tel.: +39 035 6969 362 Mob.: +39 349 2828030 Fax: +39 035 6969 400", "created_date": "2026-01-08T17:57:00Z"},
    {"name": "Massimo Rienzi", "email": "massimo.rienzi@innovagroup.it", "phone": "+39 345 091 8532", "product": "Unitree", "message": "Buongiorno, sono Massimo Rienzi e sono a contattarvi da Innova Group S.p.A. vorrei approfondire il mondo di Unitree e capire se fosse possibile fare un POC nella nostra azienda. Noi produciamo packaging in cartone ondulato e vorremmo valutare l'utilizzo di robot umanoidi per piegare scatole di grandi formati. Resto in attesa di un gentile riscontro. Cordiali saluti MR", "created_date": "2026-01-07T11:09:00Z"},
    {"name": "Pierluigi Spiezia", "email": "pspiezia@telsite.it", "phone": "+39 335 150 3773", "product": "Unitree Go2", "message": "Con questo prodotto è possibile effettuare Pattugliamento dinamico e sorveglianza?", "created_date": "2026-01-02T18:05:00Z"},
    {"name": "Antonio Capuano", "email": "antoniocapuano@hotmail.com", "phone": "+39 335 699 3912", "product": "UNITREE G1-D", "message": "Salve, dopo varie ricerche ho deciso di utilizzare i prodotti humanoid di UNITREE. Sono interessato al prodtto G1-D. Ho visto che vendete i prodotti UNITREE ma non questo. Avrei bisogno di un preventivo. Sarebbe possibile essere contattato ? Ringrazio per la disponibilità Cordiali saluti", "created_date": "2026-01-02T12:37:00Z"},
    {"name": "Chiara Tonanni", "email": "chiara.tonanni@gmail.com", "phone": "+39 329 399 0343", "product": "", "message": "Gentilissimi, utilizzo questo form per chiedervi se è possibile realizzare un piccolo desiderio di mio figlio Pietro di 8 anni. Lui fin da piccolino è sempre stato appassionato di robot, negli ultimi anni il suo interesse si è particolarmente concentrato in quanto riguarda robotica, automazione, robot umanoidi e quant'altro. Noi abitiamo molto vicini alla vostra ditta e Pietro avrebbe il grande desiderio un giorno di poterla visitare ed eventualmente vedere qualche robot in azione: sarebbe possibile? Vi ringrazio per la cortese attenzione, cordialmente Chiara Tonanni", "created_date": "2026-01-01T13:29:00Z"},
    {"name": "Deborah", "email": "acquisti@mb-fix.it", "phone": "+39 0423 913803", "product": "Robot pallettizzatore o robot caricatore pezzi", "message": "Buongiorno, sono Deborah, responsabile acquisti della ditta MB FIX di Borso del Grappa (TV). Vi contatto per chiedervi di potermi contattare al seguente numero: 0423 - 913803 e/o alla seguente mail: acquisti@mb-fix.it perchè sono interessata ad avere un breve colloquio con il vostro rappresentate, presso la nostra sede. Vorremo implementare un nuovo robot nella nostra linea di confezionamento. Quello che stiamo cercando è un robot che possa caricare i nostri prodotti (staffe in lamiera per radiatori) dal cassone alla macchina, oppure un robot che possa pallettizzare. In attesa di un gentile riscontro, porgo cordiali saluti. Deborah", "created_date": "2025-12-29T10:52:00Z"},
    {"name": "Ambrogio", "email": "ambrogio.valagussa@gmail.com", "phone": "+39 347 058 7551", "product": "Corsi", "message": "Informazioni riguardo corsi di formazione", "created_date": "2025-12-28T12:02:00Z"},
    {"name": "Rosario porfidio", "email": "az.agroforestaleporfidiorosario@gmail.com", "phone": "+39 335 632 2723", "product": "Robot unanoide", "message": "Salve sarà interessato un robot umanoide desidero essere contattato telefonicamente al numero sopra indicato", "created_date": "2025-12-22T11:15:00Z"},
    {"name": "Federico gotti", "email": "fedegotti0037@gmail.com", "phone": "+39 351 562 5797", "product": "serie w unitree", "message": "buongiorno volevo chiederle delle informazioni sull'acquisto di alcuni dei robot da voi presenti grazie mille", "created_date": "2025-12-18T18:15:00Z"},
    {"name": "Andrea Piscitelli", "email": "andrea.piscitelli@3fedin.it", "phone": "+39 345 316 8638", "product": "UNITREE B2", "message": "Buongiorno le scrivo per poter avere maggiori info per quanto riguarda acquisto/demo del dog robot unitree b2 (interessato anche al modello wheeled). Mi faccia sapere lei come possiamo organizzarci.", "created_date": "2025-12-11T10:53:00Z"},
    {"name": "Oscar", "email": "o.pistamiglio@reply.it", "phone": "+39 348 468 2987", "product": "Unitree B2 Wheeled", "message": "Buongiorno, potrei chiederti un preventivo per l'acquisto di un Unitree B2 Wheeled? Quali tempi di attesa ci sono? Molte grazie, oscar", "created_date": "2025-12-10T01:00:00Z"},
    {"name": "franzoso riccardo", "email": "ufficiotecnico@omaricelettronica.com", "phone": "+39 346 809 3661", "product": "G1-U1....U10", "message": "Richiedo maggiori informazioni per inserirlo in fabbrica per mandioni di carico e scarico curcuiti elettrici su bsnchi test devo capire quale modello e piu idoneo a wuesta mansione", "created_date": "2025-12-08T15:32:00Z"},
    {"name": "VINCENZO GRASSO", "email": "lg.energy@hotmail.com", "phone": "+39 347 291 0264", "product": "Robot Android", "message": "Vorremmo informazioni sul prodotto", "created_date": "2025-12-07T19:47:00Z"},
    {"name": "ERMENEGILDO CASARIN", "email": "e.casarin@fimap.com", "phone": "+39 335 521 4186", "product": "", "message": "Buongiorno, siamo una realtà industriale ( assemblaggio) ero interessato a capire se il G1 potrebbe fare attività di prelievo e stoccaggio Cordiali saluti Casarin Ermenegildo CIO", "created_date": "2025-12-02T15:33:00Z"},
    {"name": "Antonio Giudice", "email": "antoniogiudicecl@gmail.com", "phone": "+39 392 283 2466", "product": "Robot umanoide", "message": "Buongiorno, cercano un robot capace di fare lavori manuali i campo edilizio", "created_date": "2025-11-28T13:51:00Z"},
    {"name": "Alan James Attard Kingswell", "email": "james@kingswellinnovation.com", "phone": "+356 7906 7799", "product": "Unitree Go2 Spare Battery", "message": "Hello do you have the unitree go2 spare battery in stock, I need a second battery as soon as possible Thanks", "created_date": "2025-11-26T22:30:00Z"},
    {"name": "Simone", "email": "simoneisabella7@libero.it", "phone": "+39 331 749 3719", "product": "Unitree r1", "message": "Mi interessa il robot", "created_date": "2025-11-26T20:47:00Z"},
    {"name": "Federico", "email": "sr.srl.mo@gmail.com", "phone": "+39 334 168 9604", "product": "Unitree r1", "message": "Buongiorno avrei bisogno di più informazioni", "created_date": "2025-11-25T22:37:00Z"},
    {"name": "Lorenzo Nannini", "email": "lorenzo.nannini@powersoft.com", "phone": "+39 055 015 3435", "product": "Cobot UR", "message": "Buongiorno, la contatto dal reparto ingegneria di Powersoft. Saremmo interessati all'acquisto di un Cobot UR e ci piacerebbe fissare una call o un incontro per valutare il modello più adatto e ricevere un preventivo. Grazie in anticipo. Cordiali Saluti Lorenzo Nannini", "created_date": "2025-11-19T10:17:00Z"},
    {"name": "Carmelo Chiarenza", "email": "info@mectrotech.com", "phone": "+39 010 868 6211", "product": "robot unitree", "message": "Buongiorno la presente per richiedere la Vs migliore offerta per i seguenti prodotti Unitree - N° 1 robot G1 - N° 1 robot quadrupede GO 2 PRO Specificare tempi di consegna Grazie Carmelo Chiarenza AD", "created_date": "2025-11-15T11:43:00Z"},
    # Aggiungi altri contatti qui... (continua con tutti i 104)
]

if __name__ == '__main__':
    output_file = 'wix_submissions.json'
    
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(WIX_SUBMISSIONS, f, indent=2, ensure_ascii=False)
    
    print(f"✅ Creato file {output_file} con {len(WIX_SUBMISSIONS)} submissions")
    print(f"\n💡 Per importare:")
    print(f"   python3 utils/wix_forms_import.py {output_file}")
